### PR TITLE
chore(package.json): limit localforage version

### LINKED ISSUE #28: Prepare for localforage v1.5 upgrade
We just merged localforage/localForage#611 which adds typescript typings as part of the repo and it's planned to be released (at some point) as v1.5.0.
The respective change on localforage-cordovasqlitedriver is going to be released as v1.6.0 and is currently under the [lf1.5 branch](https://github.com/thgreasi/localForage-cordovaSQLiteDriver/tree/lf1.5).

Just giving you a note about that, in order to avoid any "duplicate identifier" errors when v1.5 gets released.
Most probably, all that needs to be done is to remove the `@types/localforage` package.
I will try to keep you posted.

### PR DESCRIPTION
**Pull request by thgreasi**
Closes #28.
As per #28 (opened @ 23 Oct), at localforage we are planning to release v1.5 that will embed the respective typings as part of the npm package.
This is hopefully going to happen before Christmas, so I guess a new ionic-storage bugfix release should be released with this change.
**Otherwise the `@types/localforage` could conflict with the embedded localforage typings.**
I will open a new PR for the next localforage release as soon as it gets released

### CODE REVIEW

**Comment by thgreasi** [comment]
> Any feedback on this? Should we proceed and release lovalforage v1.5?

**Comment by thgreasi** [comment]
Oh, and happy new year!

**Comment by thgreasi** [comment]
Reposting
> Any feedback on this? Should we proceed and release lovalforage v1.5?

**Comment by mlynch** [comment]
Thanks, makes sense! Appreciate the heads up as well.

**Pull request merged**
