### PR TITLE
feat(storage): setEngine method to choose the storage option

### PR DESCRIPTION
**Pull request by jgw96**

### CODE REVIEW

**Comment by jgw96** [comment]
The if was there to give the user an error if they did not choose one of the default ones, but i totally did not think about the fact that LocalForage accepts arbitrary engines. Ill change that.

**Comment by jgw96** [comment]
There we go, should be ready to go now.

**Comment by mlynch** [comment]
One last nitpick :) Can we call ours `setDriver` to keep it the same as localForage? No need to rename it IMO

**Comment by mlynch** [comment]
Thanks!

**Pull request merged**
